name: CI/CD Pipeline for NestJS

on:
  push:
    branches:
      - main

jobs:
  # Job 1 : Linting
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Plus besoin de spécifier la version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  # Job 2 : Tests unitaires
  unit_tests:
    runs-on: ubuntu-latest
    needs: lint  # Ce job ne s'exécute que si le linting a réussi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Plus besoin de spécifier la version

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test:unit  # Assurez-vous que ce script est défini dans votre package.json

  # Job 3 : Tests d'intégration
  integration_tests:
    runs-on: ubuntu-latest
    needs: lint  # Ce job ne s'exécute que si le linting a réussi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Plus besoin de spécifier la version

      - name: Install dependencies
        run: npm install

      - name: Run Integration Tests
        run: npm run test:integration  # Assurez-vous que ce script est défini dans votre package.json

  # Job 4 : Build
  build:
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests]  # Ce job ne s'exécute que si les tests ont réussi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Plus besoin de spécifier la version

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

  # Job 5 : Déploiement sur Heroku
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ce job ne s'exécute que si le job build a réussi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Plus besoin de spécifier la version

      - name: Install dependencies
        run: npm install

      - name: Deploy to Heroku
        uses: akshat/gh-actions-heroku@v1.0.1
        with:
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
