name: Deploy to Heroku

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Set this to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Your build script

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is a community action
        with:
          heroku_api_key: ${{ HRKU-d3ca33aa-01e0-4435-9457-7dfce8dc20e2 }}
          heroku_app_name: 'blog-api-deploy' # Set this to your Heroku app name
          heroku_email: 'patrick81.dev@gmail.com' # Set this to your Heroku account email
