name: CI/CD Pipeline for NestJS

on:
  push:
    branches:
      - main

jobs:
  # Job 1 : Linting
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Force l'utilisation de Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  # Job 2 : Tests unitaires
  e2e_tests:
    runs-on: ubuntu-latest
    needs: lint # Ce job ne s'exécute que si le linting a réussi
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Force l'utilisation de Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test:e2e # Assurez-vous que ce script est défini dans votre package.json

  # Job 3 : Build
  build:
    runs-on: ubuntu-latest
    needs: [e2e_tests] # Ce job ne s'exécute que si les tests ont réussi
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Force l'utilisation de Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

  # Job 4 : Déploiement sur Heroku
  deploy:
    runs-on: ubuntu-latest
    needs: build # Ce job ne s'exécute que si le job build a réussi
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Force l'utilisation de Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }} # Set this to your Heroku app name
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }} # Set this to your Heroku account email
